# =========================
# Application
# =========================
spring.application.name=steel-demand-platform

# =========================
# MySQL Database
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/steel_platform
spring.datasource.username=root
spring.datasource.password=1234

# =========================
# JPA
# =========================

# ? ???? '??'? ?? ? ?? ???? ?????!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true